Organi.Za.Organizaciju/ViewModels/UslugeViewModel.cs
using System.Collections.Generic;
using Organi.Za.Organizaciju.Data;

namespace Organi.Za.Organizaciju.ViewModels
{
    public class UslugeViewModel
    {
        public IEnumerable<Usluga> Usluge { get; set; }

        public IEnumerable<Oprema> PotrebnaOprema { get; set; }

        public IEnumerable<Zanimanje> PotrebnaZanimanja { get; set; }
    }
}

Organi.Za.Organizaciju/Controllers/PotrebnaOpremaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Organi.Za.Organizaciju.Data;

namespace Organi.Za.Organizaciju.Controllers
{
    public class PotrebnaOpremaController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PotrebnaOpremaController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: PotrebnaOpremas
        public async Task<IActionResult> Index(int? id)
        {
            var usluga = _context.Usluge.Find(id);

            if (usluga == null) return NotFound();

            var potrebnaOprema = await _context.PotrebnaOprema
                .Include(p => p.Usluga)
                .Include(p => p.Oprema)
                .Where(m => m.UslugaId == id).ToListAsync();

            if (potrebnaOprema == null) return NotFound();

            ViewData["UslugaId"] = id;
            ViewData["NazivUsluge"] = usluga.Naziv;

            return View(potrebnaOprema);

        }

        // GET: PotrebnaOpremas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var potrebnaOprema = await _context.PotrebnaOprema
                .Include(p => p.Oprema)
                .Include(p => p.Usluga)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (potrebnaOprema == null)
            {
                return NotFound();
            }

            return View(potrebnaOprema);
        }

        // GET: PotrebnaOpremas/Create
        public IActionResult Create(int id)
        {
            var usluga = _context.Usluge.FirstOrDefault(x => x.Id == id);

            if (usluga == null) return NotFound("Nazalost ne mozemo pronaci takvu uslugu");

            ViewData["NazivUsluge"] = usluga?.Naziv;
            ViewData["UslugaId"] = usluga?.Id;

            ViewData["OpremaId"] = new SelectList(_context.Opreme, "Id", "Naziv");
            return View();
        }

        // POST: PotrebnaOpremas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UslugaId,OpremaId,Kolicina")] PotrebnaOprema potrebnaOprema)
        {
            if (ModelState.IsValid)
            {
                potrebnaOprema.Id = 0;

                _context.Add(potrebnaOprema);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new {id = potrebnaOprema.UslugaId });
            }
            ViewData["OpremaId"] = new SelectList(_context.Opreme, "Id", "Naziv", potrebnaOprema.OpremaId);
            ViewData["UslugaId"] = new SelectList(_context.Usluge, "Id", "Naziv", potrebnaOprema.UslugaId);
            return View(potrebnaOprema);
        }

        // GET: PotrebnaOpremas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var potrebnaOprema = await _context.PotrebnaOprema.FindAsync(id);
            if (potrebnaOprema == null)
            {
                return NotFound();
            }
            ViewData["OpremaId"] = new SelectList(_context.Opreme, "Id", "Naziv", potrebnaOprema.OpremaId);
            ViewData["UslugaId"] = new SelectList(_context.Usluge, "Id", "Naziv", potrebnaOprema.UslugaId);
            return View(potrebnaOprema);
        }

        // POST: PotrebnaOpremas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UslugaId,OpremaId,Kolicina")] PotrebnaOprema potrebnaOprema)
        {
            if (id != potrebnaOprema.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(potrebnaOprema);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PotrebnaOpremaExists(potrebnaOprema.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { id = potrebnaOprema.UslugaId });
            }
            ViewData["OpremaId"] = new SelectList(_context.Opreme, "Id", "Naziv", potrebnaOprema.OpremaId);
            ViewData["UslugaId"] = new SelectList(_context.Usluge, "Id", "Naziv", potrebnaOprema.UslugaId);
            return View(potrebnaOprema);
        }

        // GET: PotrebnaOpremas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var potrebnaOprema = await _context.PotrebnaOprema
                .Include(p => p.Oprema)
                .Include(p => p.Usluga)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (potrebnaOprema == null)
            {
                return NotFound();
            }

            return View(potrebnaOprema);
        }

        // POST: PotrebnaOpremas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var potrebnaOprema = await _context.PotrebnaOprema.FindAsync(id);
            _context.PotrebnaOprema.Remove(potrebnaOprema);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { id = potrebnaOprema.UslugaId });
        }

        private bool PotrebnaOpremaExists(int id)
        {
            return _context.PotrebnaOprema.Any(e => e.Id == id);
        }
    }
}

Organi.Za.Organizaciju/Controllers/UslugeController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Organi.Za.Organizaciju.Data;
using Organi.Za.Organizaciju.ViewModels;

namespace Organi.Za.Organizaciju.Controllers
{
    public class UslugeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UslugeController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Usluge
        public async Task<IActionResult> Index(int? id)
        {
            var usluge = await _context.Usluge.Include(u => u.Kategorija).ToListAsync();

            Usluga selektiranaUsluga = null;

            if (id != null)
            {
                selektiranaUsluga = await _context.Usluge
                    .Include(x => x.PotrebnaOprema).ThenInclude(x => x.Oprema)
                    .Include(x => x.PotrebnoZanimanje).ThenInclude(x => x.Zanimanje)
                    .FirstOrDefaultAsync(x => x.Id == id);
            }

            ViewData["Id"] = id;

            var vm = new UslugeViewModel
            {
                Usluge = usluge,
                PotrebnaOprema = selektiranaUsluga?.PotrebnaOprema.Select(x => x.Oprema).ToList(),
                PotrebnaZanimanja = selektiranaUsluga?.PotrebnoZanimanje.Select(x => x.Zanimanje).ToList(),
            };

            return View(vm);
        }

        // GET: Usluge/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var usluga = await _context.Usluge
                .Include(u => u.Kategorija)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usluga == null) return NotFound();

            return View(usluga);
        }

        // GET: Usluge/Create
        public IActionResult Create()
        {
            ViewData["KategorijaId"] = new SelectList(_context.KategorijeEvenata, "Id", "Naziv");
            return View();
        }

        // POST: Usluge/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Naziv,Cijena,Opis,KategorijaId")]
            Usluga usluga)
        {
            if (ModelState.IsValid)
            {
                _context.Add(usluga);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["KategorijaId"] = new SelectList(_context.KategorijeEvenata, "Id", "Naziv", usluga.KategorijaId);
            return View(usluga);
        }

        // GET: Usluge/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var usluga = await _context.Usluge.FindAsync(id);
            if (usluga == null) return NotFound();
            ViewData["KategorijaId"] = new SelectList(_context.KategorijeEvenata, "Id", "Id", usluga.KategorijaId);
            return View(usluga);
        }

        // POST: Usluge/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naziv,Cijena,Opis,KategorijaId")]
            Usluga usluga)
        {
            if (id != usluga.Id) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usluga);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UslugaExists(usluga.Id))
                        return NotFound();
                    throw;
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["KategorijaId"] = new SelectList(_context.KategorijeEvenata, "Id", "Naziv", usluga.KategorijaId);
            return View(usluga);
        }

        // GET: Usluge/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var usluga = await _context.Usluge
                .Include(u => u.Kategorija)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usluga == null) return NotFound();

            return View(usluga);
        }

        // POST: Usluge/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usluga = await _context.Usluge.FindAsync(id);
            _context.Usluge.Remove(usluga);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UslugaExists(int id)
        {
            return _context.Usluge.Any(e => e.Id == id);
        }
    }
}

Organi.Za.Organizaciju/Views/Usluge/Create.cshtml
@model Organi.Za.Organizaciju.Data.Usluga

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Usluga</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cijena" class="control-label"></label>
                <input asp-for="Cijena" class="form-control" />
                <span asp-validation-for="Cijena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KategorijaId" class="control-label"></label>
                <select asp-for="KategorijaId" class ="form-control" asp-items="ViewBag.KategorijaId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Organi.Za.Organizaciju/Views/Usluge/Delete.cshtml
@model Organi.Za.Organizaciju.Data.Usluga

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Usluga</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cijena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cijena)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Opis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Opis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Kategorija)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Kategorija.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Organi.Za.Organizaciju/Views/Usluge/Details.cshtml
@model Organi.Za.Organizaciju.Data.Usluga

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Usluga</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cijena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cijena)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Opis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Opis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Kategorija)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Kategorija.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Organi.Za.Organizaciju/Views/Usluge/Edit.cshtml
@model Organi.Za.Organizaciju.Data.Usluga

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Usluga</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cijena" class="control-label"></label>
                <input asp-for="Cijena" class="form-control" />
                <span asp-validation-for="Cijena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KategorijaId" class="control-label"></label>
                <select asp-for="KategorijaId" class="form-control" asp-items="ViewBag.KategorijaId"></select>
                <span asp-validation-for="KategorijaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Organi.Za.Organizaciju/Views/Usluge/Index.cshtml
@model Organi.Za.Organizaciju.ViewModels.UslugeViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Popis usluga</h1>

<p>
    <a asp-action="Create">Dodaj novu</a>
</p>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                Naziv
            </th>
            <th>
                Cijena
            </th>
            <th>
                Opis
            </th>
            <th>
                Kategorija
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Usluge)
        {
            string selectedRow = "";
            if (item.Id == (int?)ViewData["Id"])
            {
                selectedRow = "table-active";
            }
            <tr class="@selectedRow">
                <td>
                    @Html.DisplayFor(modelItem => item.Naziv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cijena)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Opis)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Kategorija.Naziv)
                </td>
                <td>
                    <a asp-action="Index" asp-route-id="@item.Id">Odaberi</a>|
                    <a asp-action="Index" asp-route-id="@item.Id" asp-controller="PotrebnoZanimanja">Zanimanja</a>|
                    <a asp-action="Index" asp-route-id="@item.Id" asp-controller="PotrebnaOprema">Oprema</a>|
                    <a asp-action="Edit" asp-route-id="@item.Id">Uredi</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Detalji</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Izbrisi</a>
                </td>
            </tr>
        }
    </tbody>
</table>



@if (Model.PotrebnaZanimanja != null)
{
    <br />
    <br />
    <hr />

    <h3>Potrebna zanimanja</h3>
    <table class="table table-striped">
        <tr>
            <th>Id</th>
            <th>Naziv</th>
            <th>Opis</th>
        </tr>

        @foreach (var item in Model.PotrebnaZanimanja)
        {
            <tr>
                <td>
                    @item.Id
                </td>
                <td>
                    @item.Naziv
                </td>
                <td>
                    @item.Opis
                </td>
            </tr>
        }

    </table>
}



@if (Model.PotrebnaOprema != null)
{
    <br />
    <br />
    <hr />

    <h3>Potrebna oprema</h3>
    <table class="table table-striped">
        <tr>
            <th>Id</th>
            <th>Naziv</th>
            <th>Opis</th>
        </tr>

        @foreach (var item in Model.PotrebnaOprema)
        {
            <tr>
                <td>
                    @item.Id
                </td>
                <td>
                    @item.Naziv
                </td>
                <td>
                    @item.Opis
                </td>
            </tr>
        }

    </table>
}