Organi.Za.Organizaciju/Controllers/OsobeZaPosaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Organi.Za.Organizaciju.Data;

namespace Organi.Za.Organizaciju.Controllers
{
    public class OsobeZaPosaoController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OsobeZaPosaoController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: OsobeZaPosao
        public async Task<IActionResult> Index(int? id)
        {
            var posao = _context.SklopljeniPoslovi.Find(id);

            if (posao == null) return NotFound();

            var dodijenjeOsobe = await _context.DodijeljeneOsobe
                .Include(x => x.Osoba)
                .Include(x => x.Posao)
                .Where(x => x.PosaoId == id).ToListAsync();

            ViewData["PosaoId"] = id;
            ViewData["NazivPosla"] = posao.Naziv;

            return View(dodijenjeOsobe);
        }

        // GET: OsobeZaPosao/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dodijeljeneOsobe = await _context.DodijeljeneOsobe
                .Include(d => d.Osoba)
                .Include(d => d.Posao)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dodijeljeneOsobe == null)
            {
                return NotFound();
            }

            return View(dodijeljeneOsobe);
        }

        // GET: OsobeZaPosao/Create
        public IActionResult Create(int id)
        {
            var posao = _context.SklopljeniPoslovi.FirstOrDefault(x => x.Id == id);

            if (posao == null) return NotFound("Nazalost ne mozemo pronaci takav posao");

            ViewData["NazivPosla"] = posao?.Naziv;
            ViewData["PosaoId"] = posao?.Id;

            ViewData["OsobaId"] = new SelectList(_context.Osobe, "Id", "Ime");

            return View();
        }

        // POST: OsobeZaPosao/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,OsobaId,BrojOsoba,PosaoId")] DodijeljeneOsobe dodijeljeneOsobe)
        {
            if (ModelState.IsValid)
            {
                dodijeljeneOsobe.Id = 0;
                dodijeljeneOsobe.BrojOsoba = 1;

                var posloviOsobe = await _context.DodijeljeneOsobe.Include(x => x.Posao).Where(x => x.OsobaId == dodijeljeneOsobe.OsobaId).ToListAsync();
                var selektiraniPosao = await _context.SklopljeniPoslovi.FindAsync(dodijeljeneOsobe.PosaoId);

                ViewData["OsobaId"] = new SelectList(_context.Osobe, "Id", "Ime", dodijeljeneOsobe.OsobaId);
                ViewData["NazivPosla"] = selektiraniPosao?.Naziv;
                ViewData["PosaoId"] = selektiraniPosao?.Id;

                if (posloviOsobe != null)
                {
                    foreach (var item in posloviOsobe)
                    {

                        if (item.Posao.VrijemeRadaOd == selektiraniPosao.VrijemeRadaOd && item.Posao.VrijemeRadaDo == selektiraniPosao.VrijemeRadaDo)
                        {
                            ModelState.AddModelError(string.Empty, "Ova osoba je zauzeta za ovaj posao");
                            return View(dodijeljeneOsobe);
                        }

                        if (item.Posao.VrijemeRadaOd <= selektiraniPosao.VrijemeRadaDo && selektiraniPosao.VrijemeRadaOd <= item.Posao.VrijemeRadaDo)
                        {
                            ModelState.AddModelError(string.Empty, "Ova osoba je zauzeta za ovaj posao");
                            return View(dodijeljeneOsobe);
                        }
                    }
                }

                _context.Add(dodijeljeneOsobe);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new{id = dodijeljeneOsobe.PosaoId});
            }
            return View(dodijeljeneOsobe);
        }

        // GET: OsobeZaPosao/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dodijeljeneOsobe = await _context.DodijeljeneOsobe.Include(x => x.Posao).FirstOrDefaultAsync(x => x.Id == id);
            if (dodijeljeneOsobe == null)
            {
                return NotFound();
            }
            ViewData["OsobaId"] = new SelectList(_context.Osobe, "Id", "Ime", dodijeljeneOsobe.OsobaId);
            ViewData["NazivPosla"] = dodijeljeneOsobe?.Posao?.Naziv;
            ViewData["PosaoId"] = dodijeljeneOsobe?.Posao?.Id;
            return View(dodijeljeneOsobe);
        }

        // POST: OsobeZaPosao/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,OsobaId,BrojOsoba,PosaoId")] DodijeljeneOsobe dodijeljeneOsobe)
        {
            if (id != dodijeljeneOsobe.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    dodijeljeneOsobe.BrojOsoba = 1;
                    _context.Update(dodijeljeneOsobe);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DodijeljeneOsobeExists(dodijeljeneOsobe.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new {id=  dodijeljeneOsobe.PosaoId});
            }
            ViewData["OsobaId"] = new SelectList(_context.Osobe, "Id", "Ime", dodijeljeneOsobe.OsobaId);
            ViewData["NazivPosla"] = dodijeljeneOsobe?.Posao?.Naziv;
            ViewData["PosaoId"] = dodijeljeneOsobe?.Posao?.Id;
            return View(dodijeljeneOsobe);
        }

        // GET: OsobeZaPosao/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dodijeljeneOsobe = await _context.DodijeljeneOsobe
                .Include(d => d.Osoba)
                .Include(d => d.Posao)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dodijeljeneOsobe == null)
            {
                return NotFound();
            }

            return View(dodijeljeneOsobe);
        }

        // POST: OsobeZaPosao/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dodijeljeneOsobe = await _context.DodijeljeneOsobe.FindAsync(id);
            _context.DodijeljeneOsobe.Remove(dodijeljeneOsobe);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { id = dodijeljeneOsobe.PosaoId });
        }

        private bool DodijeljeneOsobeExists(int id)
        {
            return _context.DodijeljeneOsobe.Any(e => e.Id == id);
        }
    }
}

Organi.Za.Organizaciju/Controllers/SklopljeniPosloviController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Organi.Za.Organizaciju.Data;
using Organi.Za.Organizaciju.ViewModels;

namespace Organi.Za.Organizaciju.Controllers
{
    public class SklopljeniPosloviController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SklopljeniPosloviController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SklopljeniPoslovi
        public async Task<IActionResult> Index(int? id)
        {
            var poslovi = await _context
                .SklopljeniPoslovi
                .Include(x => x.Ponuda)
                .Include(s => s.Lokacija)
                .Include(s => s.Usluga).ToListAsync();


            SklopljeniPosao selektiraniPosao = null;

            if (id != null)
                selektiraniPosao = await _context.SklopljeniPoslovi
                    .Include(x => x.DodijeljenaOprema)
                    .ThenInclude(x => x.Oprema)
                    .Include(x => x.DodijeljeneOsobe)
                    .ThenInclude(x => x.Osoba)
                    .FirstOrDefaultAsync(x => x.Id == id);

            var vm = new PosloviViewModel
            {
                Poslovi = poslovi,
                DodijeljeneOsobe = selektiraniPosao?.DodijeljeneOsobe.Select(x => x.Osoba),
                DodideljenaOprema = selektiraniPosao?.DodijeljenaOprema.Select(x => x.Oprema)
            };

            return View(vm);
        }

        // GET: SklopljeniPoslovi/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var sklopljeniPosao = await _context.SklopljeniPoslovi
                .Include(s => s.Lokacija)
                .Include(s => s.Usluga)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sklopljeniPosao == null) return NotFound();

            return View(sklopljeniPosao);
        }

        // GET: SklopljeniPoslovi/Create
        public IActionResult Create(int? id)
        {
            var ponuda = _context.PonudaZaNatjecaj.Find(id);

            if (ponuda != null)
            {
                ViewData["PonudaId"] = ponuda.Id;
                ViewData["NazivPonude"] = ponuda.Naziv;
            }

            ViewData["LokacijaId"] = new SelectList(_context.Lokacije, "Id", "LokalniNaziv");
            ViewData["UslugaId"] = new SelectList(_context.Usluge, "Id", "Naziv");
            return View();
        }

        // POST: SklopljeniPoslovi/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Id,Naziv,Opis,UslugaId,Vrijeme,LokacijaId,DogovorenaCijena,PonudaId")]
            SklopljeniPosao sklopljeniPosao)
        {
            if (ModelState.IsValid)
            {
                sklopljeniPosao.Id = 0;
                _context.Add(sklopljeniPosao);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["LokacijaId"] =
                new SelectList(_context.Lokacije, "Id", "LokalniNaziv", sklopljeniPosao.LokacijaId);
            ViewData["UslugaId"] = new SelectList(_context.Usluge, "Id", "Naziv", sklopljeniPosao.UslugaId);
            return View(sklopljeniPosao);
        }

        // GET: SklopljeniPoslovi/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var sklopljeniPosao = await _context.SklopljeniPoslovi
                .Include(x => x.Usluga)
                .Include(x => x.Ponuda)
                .FirstOrDefaultAsync(x => x.Id == id);
            if (sklopljeniPosao == null) return NotFound();

            if (sklopljeniPosao.Ponuda != null)
            {
                ViewData["PonudaId"] = sklopljeniPosao?.Ponuda?.Id;
                ViewData["NazivPonude"] = sklopljeniPosao?.Ponuda?.Naziv;
            }

            ViewData["LokacijaId"] =
                new SelectList(_context.Lokacije, "Id", "LokalniNaziv", sklopljeniPosao.LokacijaId);
            ViewData["UslugaId"] = new SelectList(_context.Usluge, "Id", "Naziv", sklopljeniPosao.UslugaId);
            return View(sklopljeniPosao);
        }

        // POST: SklopljeniPoslovi/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,
            [Bind("Id,Naziv,Opis,UslugaId,Vrijeme,LokacijaId,DogovorenaCijena,PonudaId")]
            SklopljeniPosao sklopljeniPosao)
        {
            if (id != sklopljeniPosao.Id) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sklopljeniPosao);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SklopljeniPosaoExists(sklopljeniPosao.Id))
                        return NotFound();
                    throw;
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["LokacijaId"] =
                new SelectList(_context.Lokacije, "Id", "LokalniNaziv", sklopljeniPosao.LokacijaId);
            ViewData["UslugaId"] = new SelectList(_context.Usluge, "Id", "Naziv", sklopljeniPosao.UslugaId);
            return View(sklopljeniPosao);
        }

        // GET: SklopljeniPoslovi/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var sklopljeniPosao = await _context.SklopljeniPoslovi
                .Include(s => s.Lokacija)
                .Include(s => s.Usluga)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sklopljeniPosao == null) return NotFound();

            return View(sklopljeniPosao);
        }

        // POST: SklopljeniPoslovi/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sklopljeniPosao = await _context.SklopljeniPoslovi.FindAsync(id);
            _context.SklopljeniPoslovi.Remove(sklopljeniPosao);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SklopljeniPosaoExists(int id)
        {
            return _context.SklopljeniPoslovi.Any(e => e.Id == id);
        }
    }
}

Organi.Za.Organizaciju/Views/SklopljeniPoslovi/Create.cshtml
@model Organi.Za.Organizaciju.Data.SklopljeniPosao

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SklopljeniPosao</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @{
                if (ViewData["PonudaId"] != null)
                {
                    <div class="form-group">
                        <label asp-for="PonudaId" class="control-label">Odabrana ponuda (nije moguće mijenjati)</label>
                        <input asp-for="PonudaId" hidden="hidden" value="@ViewData["PonudaId"]"/>
                        <span class="form-control disabled" >@ViewData["NazivPonude"]</span>
                        <span asp-validation-for="PonudaId" class="text-danger"></span>
                    </div>
                }
                else
                {
                    <div class="form-group">
                        <label asp-for="UslugaId" class="control-label"></label>
                        <select asp-for="UslugaId" class="form-control" asp-items="ViewBag.UslugaId"></select>
                        <span asp-validation-for="UslugaId" class="text-danger"></span>
                    </div>
                }
            }
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control" />
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" class="form-control" />
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>
         
            <div class="form-group">
                <label asp-for="VrijemeRadaOd" class="control-label"></label>
                <input asp-for="VrijemeRadaOd" class="form-control" />
                <span asp-validation-for="VrijemeRadaOd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VrijemeRadaDo" class="control-label"></label>
                <input asp-for="VrijemeRadaDo" class="form-control" />
                <span asp-validation-for="VrijemeRadaDo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LokacijaId" class="control-label"></label>
                <select asp-for="LokacijaId" class ="form-control" asp-items="ViewBag.LokacijaId"></select>
            </div>
            <div class="form-group">
                <label asp-for="DogovorenaCijena" class="control-label"></label>
                <input asp-for="DogovorenaCijena" class="form-control" />
                <span asp-validation-for="DogovorenaCijena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Organi.Za.Organizaciju/Views/SklopljeniPoslovi/Delete.cshtml
@model Organi.Za.Organizaciju.Data.SklopljeniPosao

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SklopljeniPosao</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Opis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Opis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usluga)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usluga.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VrijemeRadaOd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VrijemeRadaOd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lokacija)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lokacija.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DogovorenaCijena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DogovorenaCijena)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Organi.Za.Organizaciju/Views/SklopljeniPoslovi/Details.cshtml
@model Organi.Za.Organizaciju.Data.SklopljeniPosao

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SklopljeniPosao</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Opis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Opis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usluga)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usluga.Naziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.VrijemeRadaOd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.VrijemeRadaOd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lokacija)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lokacija.LokalniNaziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DogovorenaCijena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DogovorenaCijena)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Organi.Za.Organizaciju/Views/SklopljeniPoslovi/Edit.cshtml
@model Organi.Za.Organizaciju.Data.SklopljeniPosao

@{
    ViewData["Title"] = "Edit";
}


<h4>Uredi sklopljeni posao</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            @{
                if (ViewData["PonudaId"] != null)
                {
                    <div class="form-group">
                        <label asp-for="PonudaId" class="control-label">Odabrana ponuda (nije moguće mijenjati)</label>
                        <input asp-for="PonudaId" hidden="hidden" value="@ViewData["PonudaId"]"/>
                        <span class="form-control disabled" >@ViewData["NazivPonude"]</span>
                        <span asp-validation-for="PonudaId" class="text-danger"></span>
                    </div>
                }
                else
                {
                    <div class="form-group">
                        <label asp-for="UslugaId" class="control-label"></label>
                        <select asp-for="UslugaId" class="form-control" asp-items="ViewBag.UslugaId"></select>
                        <span asp-validation-for="UslugaId" class="text-danger"></span>
                    </div>
                }
            }
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id"/>
            <div class="form-group">
                <label asp-for="Naziv" class="control-label"></label>
                <input asp-for="Naziv" class="form-control"/>
                <span asp-validation-for="Naziv" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opis" class="control-label"></label>
                <input asp-for="Opis" class="form-control"/>
                <span asp-validation-for="Opis" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="VrijemeRadaOd" class="control-label"></label>
                <input asp-for="VrijemeRadaOd" class="form-control"/>
                <span asp-validation-for="VrijemeRadaOd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VrijemeRadaDo" class="control-label"></label>
                <input asp-for="VrijemeRadaDo" class="form-control" />
                <span asp-validation-for="VrijemeRadaDo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LokacijaId" class="control-label"></label>
                <select asp-for="LokacijaId" class="form-control" asp-items="ViewBag.LokacijaId"></select>
                <span asp-validation-for="LokacijaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DogovorenaCijena" class="control-label"></label>
                <input asp-for="DogovorenaCijena" class="form-control"/>
                <span asp-validation-for="DogovorenaCijena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Organi.Za.Organizaciju/Views/SklopljeniPoslovi/Index.cshtml
@model Organi.Za.Organizaciju.ViewModels.PosloviViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Sklopljeni poslovi</h1>

<p>
    <a asp-action="Create">Sklopi novi posao</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Naziv
            </th>
            <th>
                Opis
            </th>
            <th>
                Usluga / Ponuda
            </th>
            <th>
                Vrijeme Od
            </th>
            <th>
                Vrijeme Do
            </th>
            <th>
                Lokacija
            </th>
            <th>
                Cijena
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Poslovi)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Opis)
            </td>
        
            @{
                if (item.Usluga != null)
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.Usluga.Naziv)
                    </td>
                }
                else
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.Ponuda.Naziv)
                    </td>
                }
            }
            <td>
                @Html.DisplayFor(modelItem => item.VrijemeRadaOd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VrijemeRadaDo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lokacija.LokalniNaziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DogovorenaCijena)
            </td>
            <td>
                <a asp-action="Index" asp-route-id="@item.Id">Pregled  </a>|
                <a asp-action="Index" asp-controller="OsobeZaPosao" asp-route-id="@item.Id">Dodaj osobe</a>|
                <a asp-action="Index" asp-controller="DodijeljenaOprema" asp-route-id="@item.Id">Dodaj opremu</a>|
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>



@if (Model.DodideljenaOprema != null)
{
    <br />
    <br />
    <hr />

    <h3>Oprema</h3>
    <table class="table">
        <tr>
            <th>Id</th>
            <th>Naziv</th>
            <th>Kolicina</th>
            <th>Invertarni broj</th>
        </tr>

        @foreach (var item in Model.DodideljenaOprema)
        {
            <tr>
                <td>
                    @item.Id
                </td>
                <td>
                    @item.Naziv
                </td>
                <td>
                    @item.Kolicina
                </td>
                <td>
                    @item.InvertarniBroj
                </td>
            </tr>
        }

    </table>
}

@if (Model.DodijeljeneOsobe != null)
{
    <br />
    <br />
    <hr />

    <h3>Osobe</h3>
    <table class="table">
        <tr>
            <th>Id</th>
            <th>Ime </th>
            <th>Prezime </th>
        </tr>

        @foreach (var item in Model.DodijeljeneOsobe)
        {
            <tr>
                <td>
                    @item.Id
                </td>
                <td>
                    @item.Ime
                </td>
                <td>
                    @item.Prezime
                </td>
            </tr>
        }

    </table>
}