Organi.Za.Organizaciju/Controllers/PotrebnaOpremaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Organi.Za.Organizaciju.Data;

namespace Organi.Za.Organizaciju.Controllers
{
    public class PotrebnaOpremaController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PotrebnaOpremaController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: PotrebnaOpremas
        public async Task<IActionResult> Index(int? id)
        {
            var usluga = _context.Usluge.Find(id);

            if (usluga == null) return NotFound();

            var potrebnaOprema = await _context.PotrebnaOprema
                .Include(p => p.Usluga)
                .Include(p => p.Oprema)
                .Where(m => m.UslugaId == id).ToListAsync();

            if (potrebnaOprema == null) return NotFound();

            ViewData["UslugaId"] = id;
            ViewData["NazivUsluge"] = usluga.Naziv;

            return View(potrebnaOprema);

        }

        // GET: PotrebnaOpremas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var potrebnaOprema = await _context.PotrebnaOprema
                .Include(p => p.Oprema)
                .Include(p => p.Usluga)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (potrebnaOprema == null)
            {
                return NotFound();
            }

            return View(potrebnaOprema);
        }

        // GET: PotrebnaOpremas/Create
        public IActionResult Create(int id)
        {
            var usluga = _context.Usluge.FirstOrDefault(x => x.Id == id);

            if (usluga == null) return NotFound("Nazalost ne mozemo pronaci takvu uslugu");

            ViewData["NazivUsluge"] = usluga?.Naziv;
            ViewData["UslugaId"] = usluga?.Id;

            ViewData["OpremaId"] = new SelectList(_context.Opreme, "Id", "Naziv");
            return View();
        }

        // POST: PotrebnaOpremas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UslugaId,OpremaId,Kolicina")] PotrebnaOprema potrebnaOprema)
        {
            if (ModelState.IsValid)
            {
                potrebnaOprema.Id = 0;

                _context.Add(potrebnaOprema);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new {id = potrebnaOprema.UslugaId });
            }
            ViewData["OpremaId"] = new SelectList(_context.Opreme, "Id", "Naziv", potrebnaOprema.OpremaId);
            ViewData["UslugaId"] = new SelectList(_context.Usluge, "Id", "Naziv", potrebnaOprema.UslugaId);
            return View(potrebnaOprema);
        }

        // GET: PotrebnaOpremas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var potrebnaOprema = await _context.PotrebnaOprema.FindAsync(id);
            if (potrebnaOprema == null)
            {
                return NotFound();
            }
            ViewData["OpremaId"] = new SelectList(_context.Opreme, "Id", "Naziv", potrebnaOprema.OpremaId);
            ViewData["UslugaId"] = new SelectList(_context.Usluge, "Id", "Naziv", potrebnaOprema.UslugaId);
            return View(potrebnaOprema);
        }

        // POST: PotrebnaOpremas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UslugaId,OpremaId,Kolicina")] PotrebnaOprema potrebnaOprema)
        {
            if (id != potrebnaOprema.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(potrebnaOprema);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PotrebnaOpremaExists(potrebnaOprema.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { id = potrebnaOprema.UslugaId });
            }
            ViewData["OpremaId"] = new SelectList(_context.Opreme, "Id", "Naziv", potrebnaOprema.OpremaId);
            ViewData["UslugaId"] = new SelectList(_context.Usluge, "Id", "Naziv", potrebnaOprema.UslugaId);
            return View(potrebnaOprema);
        }

        // GET: PotrebnaOpremas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var potrebnaOprema = await _context.PotrebnaOprema
                .Include(p => p.Oprema)
                .Include(p => p.Usluga)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (potrebnaOprema == null)
            {
                return NotFound();
            }

            return View(potrebnaOprema);
        }

        // POST: PotrebnaOpremas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var potrebnaOprema = await _context.PotrebnaOprema.FindAsync(id);
            _context.PotrebnaOprema.Remove(potrebnaOprema);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { id = potrebnaOprema.UslugaId });
        }

        private bool PotrebnaOpremaExists(int id)
        {
            return _context.PotrebnaOprema.Any(e => e.Id == id);
        }
    }
}

Organi.Za.Organizaciju/Controllers/UslugeController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Organi.Za.Organizaciju.Data;
using Organi.Za.Organizaciju.ViewModels;

namespace Organi.Za.Organizaciju.Controllers
{
    public class UslugeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UslugeController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Usluge
        public async Task<IActionResult> Index(int? id)
        {
            var usluge = await _context.Usluge.Include(u => u.Kategorija).ToListAsync();

            Usluga selektiranaUsluga = null;

            if (id != null)
            {
                selektiranaUsluga = await _context.Usluge
                    .Include(x => x.PotrebnaOprema).ThenInclude(x => x.Oprema)
                    .Include(x => x.PotrebnoZanimanje).ThenInclude(x => x.Zanimanje)
                    .FirstOrDefaultAsync(x => x.Id == id);
            }

            ViewData["Id"] = id;

            var vm = new UslugeViewModel
            {
                Usluge = usluge,
                PotrebnaOprema = selektiranaUsluga?.PotrebnaOprema.Select(x => x.Oprema).ToList(),
                PotrebnaZanimanja = selektiranaUsluga?.PotrebnoZanimanje.Select(x => x.Zanimanje).ToList(),
            };

            return View(vm);
        }

        // GET: Usluge/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var usluga = await _context.Usluge
                .Include(u => u.Kategorija)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usluga == null) return NotFound();

            return View(usluga);
        }

        // GET: Usluge/Create
        public IActionResult Create()
        {
            ViewData["KategorijaId"] = new SelectList(_context.KategorijeEvenata, "Id", "Naziv");
            return View();
        }

        // POST: Usluge/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Naziv,Cijena,Opis,KategorijaId")]
            Usluga usluga)
        {
            if (ModelState.IsValid)
            {
                _context.Add(usluga);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["KategorijaId"] = new SelectList(_context.KategorijeEvenata, "Id", "Naziv", usluga.KategorijaId);
            return View(usluga);
        }

        // GET: Usluge/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var usluga = await _context.Usluge.FindAsync(id);
            if (usluga == null) return NotFound();
            ViewData["KategorijaId"] = new SelectList(_context.KategorijeEvenata, "Id", "Id", usluga.KategorijaId);
            return View(usluga);
        }

        // POST: Usluge/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naziv,Cijena,Opis,KategorijaId")]
            Usluga usluga)
        {
            if (id != usluga.Id) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usluga);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UslugaExists(usluga.Id))
                        return NotFound();
                    throw;
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["KategorijaId"] = new SelectList(_context.KategorijeEvenata, "Id", "Naziv", usluga.KategorijaId);
            return View(usluga);
        }

        // GET: Usluge/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var usluga = await _context.Usluge
                .Include(u => u.Kategorija)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usluga == null) return NotFound();

            return View(usluga);
        }

        // POST: Usluge/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usluga = await _context.Usluge.FindAsync(id);
            _context.Usluge.Remove(usluga);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UslugaExists(int id)
        {
            return _context.Usluge.Any(e => e.Id == id);
        }
    }
}

Organi.Za.Organizaciju/Views/PotrebnaOprema/Create.cshtml
@model Organi.Za.Organizaciju.Data.PotrebnaOprema

@{
    ViewData["Title"] = "Create";
}

<h1>Dodaj</h1>

<h4>Novi tip oprema za uslugu: <strong>@ViewData["NazivUsluge"]</strong></h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UslugaId" class="control-label">Odabrana usluga (nije moguće mijenjati)</label>
                <input asp-for="UslugaId" hidden="hidden" value="@ViewData["UslugaId"]"/>
                <span class="form-control disabled" >@ViewData["NazivUsluge"]</span>
                <span asp-validation-for="UslugaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpremaId" class="control-label">Oprema</label>
                <select asp-for="OpremaId" class ="form-control" asp-items="ViewBag.OpremaId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Kolicina" class="control-label"></label>
                <input asp-for="Kolicina" class="form-control" />
                <span asp-validation-for="Kolicina" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-route-id="@ViewData["UslugaId"]" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Organi.Za.Organizaciju/Views/PotrebnaOprema/Delete.cshtml
@model Organi.Za.Organizaciju.Data.PotrebnaOprema

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PotrebnaOprema</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usluga)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usluga.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Oprema)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Oprema.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Kolicina)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Kolicina)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-route-id="@Model.UslugaId" asp-action="Index">Back to List</a>
    </form>
</div>

Organi.Za.Organizaciju/Views/PotrebnaOprema/Details.cshtml
@model Organi.Za.Organizaciju.Data.PotrebnaOprema

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>PotrebnaOprema</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usluga)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usluga.Naziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Oprema)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Oprema.Naziv)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Kolicina)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Kolicina)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-route-id="@Model.UslugaId" asp-action="Index">Nazad</a>
</div>

Organi.Za.Organizaciju/Views/PotrebnaOprema/Edit.cshtml
@model Organi.Za.Organizaciju.Data.PotrebnaOprema

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>PotrebnaOprema</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UslugaId" class="control-label"></label>
                <select asp-for="UslugaId" class="form-control" asp-items="ViewBag.UslugaId"></select>
                <span asp-validation-for="UslugaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpremaId" class="control-label"></label>
                <select asp-for="OpremaId" class="form-control" asp-items="ViewBag.OpremaId"></select>
                <span asp-validation-for="OpremaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kolicina" class="control-label"></label>
                <input asp-for="Kolicina" class="form-control" />
                <span asp-validation-for="Kolicina" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-route-id="@Model.UslugaId" asp-action="Index">Nazad</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Organi.Za.Organizaciju/Views/PotrebnaOprema/Index.cshtml
@model IEnumerable<Organi.Za.Organizaciju.Data.PotrebnaOprema>

@{
    ViewData["Title"] = "Index";
}

<h3>Potrebna oprema za uslugu: &nbsp; <strong>   @ViewData["NazivUsluge"]</strong></h3>

<p>
    <a asp-route-id="@ViewData["UslugaId"]" asp-action="Create">Dodaj novu opremu</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Usluga)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Oprema)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Kolicina)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Usluga.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Oprema.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Kolicina)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>

<br/>
<hr/>
<a asp-action="Index" asp-controller="Usluge">Nazad na usluge</a> 